apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: locust-worker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: locust-worker   # Nombre del despliegue de Locust Workers
  minReplicas: 3          # Mínimo de pods (Locust Workers)
  maxReplicas: 100         # Máximo de pods (hasta 50 Workers si es necesario)
  targetCPUUtilizationPercentage: 80  # Escalará cuando el uso de CPU alcance el 80%
