apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: locust-worker
    app: locust-worker
  name: locust-worker
  namespace: locust-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      role: locust-worker
      app: locust-worker
  template:
    metadata:
      labels:
        role: locust-worker
        app: locust-worker
    spec:
      containers:
      - image: locustio/locust
        imagePullPolicy: Always
        name: worker
        args: ["--worker", "--master-host=locust-master"]
        resources:
          requests:
            cpu: "200m"  # Solicitará al menos 200 millicores de CPU
          limits:
            cpu: "500m"  # Usará como máximo 500 millicores de CPU
        volumeMounts:
          - mountPath: /home/locust
            name: locust-scripts
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      schedulerName: default-scheduler
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: locust-scripts
        configMap:
          name: locustfile-scripts
