apiVersion: v1
kind: ConfigMap
metadata:
  name: locustfile-cm
  namespace: load-testing
data:
  locustfile.py: |
    from locust import HttpUser, task, between

    class WebsiteUser(HttpUser):
        # Espera entre 1 y 2 segundos entre las solicitudes
        wait_time = between(1, 2)

        # Define el host de la página web que quieres testear
        host = "http://pagina-web.com"

        # Configura el proxy de Envoy
        proxies = {
            "http": "http://envoy-service:8080",  # Asegúrate de que este es el puerto de Envoy
            "https": "http://envoy-service:8080"
        }

        @task
        def load_page(self):
            # Enviar una solicitud GET a la página principal
            self.client.get("/", proxies=self.proxies)