apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: locust-worker-hpa
  namespace: locust-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: locust-worker
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75
