apiVersion: v1
kind: Service
metadata:
  labels:
    role: locust-master
  name: locust-master-internal  # Servicio interno para comunicación de trabajadores
  namespace: load-testing
spec:
  type: ClusterIP  # Solo accesible dentro del clúster
  ports:
  - port: 5557  # Comunicación maestro-trabajadores
    targetPort: 5557
    name: mas-wor-comm
  - port: 5558  # Sincronización de trabajadores
    targetPort: 5558
    name: worker-syn
  selector:
    role: locust-master
    app: locust-master
