apiVersion: v1
kind: ConfigMap
metadata:
  name: locustfile-cm
  namespace: load-testing
data:
  locustfile.py: |
    from locust import HttpUser, task, between

    class UserBehavior(HttpUser):
        wait_time = between(1, 5)  # Tiempo de espera entre solicitudes

        @task
        def attack_vm(self):
            self.client.get("/")  # Realiza una solicitud GET a la VM
