apiVersion: v1
kind: Service
metadata:
  labels:
    role: locust-master
  name: locust-master
  namespace: locust-namespace  # Asegúrate de que el namespace sea correcto
spec:
  type: LoadBalancer            # Cambia a LoadBalancer
  ports:
  - port: 5557
    name: communication
  - port: 5558
    name: communication-plus-1
  - port: 8089
    targetPort: 8089
    name: web-ui                # Puerto de la interfaz web de Locust
  selector:
    role: locust-master
    app: locust-master