apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
    - name: service
      port: 80
      targetPort: 3000
  selector:
    app.kubernetes.io/name: grafana
