apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: monitoring
type: Opaque
data:
  admin-user: "YWRtaW4="  # admin en base64
  admin-password: "bXktc2VjcmV0LXBhc3N3b3Jk"  # my-secret-password en base64
