apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: envoy-hpa
  namespace: load-testing
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: envoy-egress-proxy
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: envoy_http_requests_total
      target:
        type: AverageValue
        averageValue: 100  # Ajusta este valor según tu carga de pruebas
