apiVersion: v1
kind: Service
metadata:
  name: envoy-service
  namespace: load-testing
spec:
  selector:
    app: envoy
  ports:
    - name: http-port
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: admin
      protocol: TCP
      port: 9901
      targetPort: 9901
  type: ClusterIP
