apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 1m
      evaluation_interval: 1m
      scrape_timeout: 10s

    rule_files:
      - /etc/config/recording_rules.yml
      - /etc/config/alerting_rules.yml
      - /etc/config/rules
      - /etc/config/alerts

    scrape_configs:  
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'envoy'
        scrape_interval: 15s
        static_configs:
          - targets: ['envoy-service.load-testing.svc.cluster.local:9901']
        metrics_path: /stats/prometheus