apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP  # Solo accesible dentro del clúster
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx

