apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: locust-testing  # Namespace donde se encuentran los recursos que Prometheus monitoreará
  name: prometheus-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
