apiVersion: v1
kind: Service
metadata:
  labels:
    role: locust-master
  name: locust-master
  namespace: load-testing
spec:
  type: LoadBalancer  # Mantén LoadBalancer solo para el puerto web
  ports:
  - port: 8089  # Exponer solo el puerto 8089 públicamente
    targetPort: 8089
    name: load-web
  selector:
    role: locust-master
    app: locust-master

