apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: LoadBalancer  # Expone el servicio de forma externa (puedes usar ClusterIP para acceso interno)
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000